name: CI/CD for Azure Functions

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Azure Functions
      env:
        AZURE_FUNCTIONAPP_NAME: sahtestfunctions
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_TENANT_ID: 98e60346-ad63-4f8f-9160-5799700083d3
      run: |
        az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET --tenant $AZURE_TENANT_ID
        func azure functionapp publish $AZURE_FUNCTIONAPP_NAME --javascript

