name: Azure Functions CI/CD

on:
  push:
    branches:
      - main  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clear npm cache
        run: npm cache clean --force
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          path: AzureFunctionsTutorial

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 10.1.0  
          

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Azure CLI
        uses: azure/setup-python@v2
        with:
          python-version: '3.x'

      - name: Add Az CLI to PATH
        run: |
          echo "$RUNNER_TOOL_CACHE/az/2.53.1/x64" >> $GITHUB_PATH  
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Functions
        env:
          AZURE_FUNCTIONAPP_NAME: sahtestfunctions
          AZURE_FUNCTIONAPP_PACKAGE_PATH: AzurefunctionsTutorial  
          AZURE_FUNCTIONAPP_DEPLOY_METHOD: zipdeploy
        uses: azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          deploy-method: ${{ env.AZURE_FUNCTIONAPP_DEPLOY_METHOD }}
          slot-name: production  
