name: CI/CD for Azure Functions

on:
  push:
    branches:
      - main  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
     
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Install Azure Functions Core Tools
      run: npm install -g azure-functions-core-tools@3 --unsafe-perm true
      
    - name: Deploy to Azure Functions
      env:
        AZURE_FUNCTIONAPP_NAME: sahtestfunctions
      run: |
        az login --service-principal -u ${{ secrets.AZURE_CLIENT_ID }} -p ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        func azure functionapp publish $AZURE_FUNCTIONAPP_NAME --javascript

