name: Azure Functions CI/CD

on:
  push:
    branches:
      - main 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6 

    - name: Build
      run: dotnet build

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish

    - name: Deploy to Azure Functions
      uses: azure/webapps-deploy@v2
      with:
        app-name: sahtestfunctions 
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
